# Generated by Django 6.0 on 2025-12-10 14:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Nom de la ferme"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Nom de la rue et numéro du lieu de production.",
                        max_length=250,
                        null=True,
                        verbose_name="Adresse du lieu de production",
                    ),
                ),
                (
                    "GPS_coordinates",
                    models.CharField(
                        blank=True,
                        help_text="latitude, longitude du lieu de production (tel qu'extrait via un clic-droit sur Google Maps)",
                        max_length=40,
                        null=True,
                        verbose_name="Coordonnées GPS",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Doit commencer par http:// ou https://.",
                        null=True,
                        unique=True,
                        verbose_name="Site web",
                    ),
                ),
                (
                    "fb_page",
                    models.URLField(
                        blank=True, null=True, unique=True, verbose_name="Page Facebook"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=250,
                        null=True,
                        unique=True,
                        verbose_name="Adresse email",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Peut être un numéro fixe ou GSM.",
                        max_length=128,
                        null=True,
                        region="BE",
                        unique=True,
                        verbose_name="N° de téléphone",
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        help_text="Cela n'engage à rien d'autre qu'à peut-être un jour être contacté·e.",
                        verbose_name="J'accepte d'être contacté·e par l'UCLouvain pour des questions de recherche liées au maraîchage diversifié.",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Surface dédiée à la production de légumes (en ha)",
                    ),
                ),
                (
                    "FTE",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Nombre d'équivalents temps plein rémunérés",
                    ),
                ),
                (
                    "production",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bio certifié", "Bio certifié"),
                            ("Bio non-certifié", "Bio non-certifié"),
                            ("Conventionnel", "Conventionnel"),
                        ],
                        null=True,
                        verbose_name="Mode de production",
                    ),
                ),
                (
                    "start_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Année d'installation"
                    ),
                ),
                (
                    "end_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Laisser vide si le projet est toujours actif.",
                        null=True,
                        verbose_name="Année de fin d'activité (le cas échéant)",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Commentaire(s)",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si la ferme maraîchère est listée sur la plateforme ou non.",
                        verbose_name="Public",
                    ),
                ),
                (
                    "flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Permet de marquer une ferme en cas de doute sur les données. (Utiliser le champ commentaire pour détailler.)",
                        verbose_name="Flagged",
                    ),
                ),
                (
                    "edited_by_user",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si les données ont été éditées par un·e utilisateur·rice.",
                        verbose_name="Edited by user",
                    ),
                ),
                (
                    "added_by",
                    models.CharField(
                        choices=[("Staff", "Staff"), ("User", "User")],
                        default="User",
                        help_text="Indique si la ferme a été ajoutée par un utilisateur de la plateforme ou non.",
                        verbose_name="Ajouté par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ferme",
                "verbose_name_plural": "Fermes",
            },
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Nom"),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("Brabant flamand", "Brabant flamand"),
                            ("Brabant wallon", "Brabant wallon"),
                            ("Bruxelles", "Bruxelles"),
                            ("Hainaut", "Hainaut"),
                            ("Liège", "Liège"),
                            ("Luxembourg", "Luxembourg"),
                            ("Namur", "Namur"),
                        ],
                        verbose_name="Province",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Surface (en km²)"
                    ),
                ),
                (
                    "population",
                    models.IntegerField(verbose_name="Population (au 01/01/2025)"),
                ),
            ],
            options={
                "verbose_name": "Commune",
                "verbose_name_plural": "Communes",
            },
        ),
        migrations.CreateModel(
            name="ExpiringUniqueEditLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Token d'accès unique"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(verbose_name="Date d'expiration"),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="census.farm",
                        verbose_name="Ferme associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien d'édition",
                "verbose_name_plural": "Liens d'édition",
            },
        ),
        migrations.AddField(
            model_name="farm",
            name="municipality",
            field=models.ForeignKey(
                help_text="Parmi les 261 communes wallonnes, les 19 communes bruxelloises et les 6 communes à facilités.",
                on_delete=django.db.models.deletion.PROTECT,
                to="census.municipality",
                verbose_name="Commune du lieu de production",
            ),
        ),
        migrations.CreateModel(
            name="OtherLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100, verbose_name="Auteur")),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("link", models.URLField(unique=True, verbose_name="Lien")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="census.farm",
                        verbose_name="Ferme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autre lien",
                "verbose_name_plural": "Autres liens",
            },
        ),
        migrations.CreateModel(
            name="MarketGardener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50, verbose_name="Prénom")),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom de famille"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default=None,
                        help_text="N° de téléphone personnel.",
                        max_length=128,
                        null=True,
                        region="BE",
                        unique=True,
                        verbose_name="N° de téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        help_text="Adresse email personnelle liée au projet si elle existe.",
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Adresse email",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="census.farm",
                        verbose_name="Ferme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maraîcher·ère",
                "verbose_name_plural": "Maraîcher·ères",
                "unique_together": {("firstname", "lastname")},
            },
        ),
    ]
