# Generated by Django 5.2.8 on 2025-12-02 10:43

import django.db.models.deletion
import location_field.models.plain
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Nom de la ferme"),
                ),
                (
                    "GPS_coordinates",
                    location_field.models.plain.PlainLocationField(max_length=63),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Surface (en ha)"
                    ),
                ),
                (
                    "FTE",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        verbose_name="Nombre d'équivalent temps plein (ETP)",
                    ),
                ),
                ("start_year", models.DateField(verbose_name="Année d'installation")),
                (
                    "end_year",
                    models.DateField(verbose_name="Fin du projet (si arrêté)"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse e-mail"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="BE",
                        unique=True,
                        verbose_name="N° de téléphone",
                    ),
                ),
                ("website", models.URLField(unique=True, verbose_name="Site web")),
                ("fb_page", models.URLField(unique=True, verbose_name="Page Facebook")),
                (
                    "comment",
                    models.TextField(max_length=1000, verbose_name="Commentaire(s)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Nom"),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("Brabant flamand", "Brabant flamand"),
                            ("Brabant wallon", "Brabant wallon"),
                            ("Bruxelles", "Bruxelles"),
                            ("Hainaut", "Hainaut"),
                            ("Liège", "Liège"),
                            ("Luxembourg", "Luxembourg"),
                            ("Namur", "Namur"),
                        ],
                        verbose_name="Province",
                    ),
                ),
                (
                    "population",
                    models.IntegerField(verbose_name="Population (au 01/01/2025)"),
                ),
                ("area", models.IntegerField(verbose_name="Surface (en km²)")),
            ],
        ),
        migrations.CreateModel(
            name="MarketGardener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50, verbose_name="Prénom")),
                ("lastname", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="census.farm",
                        verbose_name="Ferme",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="farm",
            name="municipality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="census.municipality",
                verbose_name="Commune",
            ),
        ),
    ]
