# Generated by Django 5.2.8 on 2025-12-02 14:12

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={"verbose_name": "Ferme", "verbose_name_plural": "Fermes"},
        ),
        migrations.AlterModelOptions(
            name="marketgardener",
            options={
                "verbose_name": "Maraîcher·ère",
                "verbose_name_plural": "Maraîcher·ères",
            },
        ),
        migrations.AlterModelOptions(
            name="municipality",
            options={"verbose_name": "Commune", "verbose_name_plural": "Communes"},
        ),
        migrations.AddField(
            model_name="farm",
            name="production",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bio certifié", "Bio certifié"),
                    ("Bio non-certifié", "Bio non-certifié"),
                    ("Conventionnel", "Conventionnel"),
                ],
                verbose_name="Mode de production",
            ),
        ),
        migrations.AddField(
            model_name="marketgardener",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region="BE",
                unique=True,
                verbose_name="N° de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="FTE",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                verbose_name="Nombre d'équivalent temps plein (ETP)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="GPS_coordinates",
            field=models.CharField(
                blank=True,
                help_text="latitude, longitude (tel qu'extrait via un clic-droit sur Google Maps)",
                max_length=35,
                verbose_name="Coordonnées GPS",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                verbose_name="Surface (en ha)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="comment",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Commentaire(s)"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="end_year",
            field=models.IntegerField(
                blank=True,
                help_text="Laisser vide si le projet est toujours actif.",
                verbose_name="Année de l'arrêt (si fini)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="fb_page",
            field=models.URLField(
                blank=True, unique=True, verbose_name="Page Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="municipality",
            field=models.ForeignKey(
                help_text="Parmi les 261 communes wallones, les 19 communes bruxelloises et les 6 communes à facilités.",
                on_delete=django.db.models.deletion.PROTECT,
                to="census.municipality",
                verbose_name="Commune",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region="BE",
                unique=True,
                verbose_name="N° de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="start_year",
            field=models.IntegerField(blank=True, verbose_name="Année d'installation"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Pertinent même si le lien ne fonctionne plus (via Internet Wayback Machine).",
                unique=True,
                verbose_name="Site web",
            ),
        ),
        migrations.AlterField(
            model_name="marketgardener",
            name="firstname",
            field=models.CharField(blank=True, max_length=50, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="marketgardener",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nom de famille"
            ),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="area",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Surface (en km²)"
            ),
        ),
        migrations.CreateModel(
            name="OtherLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100, verbose_name="Auteur")),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Pertinent même si le lien ne fonctionne plus (via Internet Wayback Machine).",
                        unique=True,
                        verbose_name="Lien",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="census.farm",
                        verbose_name="Ferme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autre lien",
                "verbose_name_plural": "Autres liens",
            },
        ),
    ]
