# Generated by Django 6.0 on 2025-12-10 14:20

import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalFarm",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Nom de la ferme"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Nom de la rue et numéro du lieu de production.",
                        max_length=250,
                        null=True,
                        verbose_name="Adresse du lieu de production",
                    ),
                ),
                (
                    "GPS_coordinates",
                    models.CharField(
                        blank=True,
                        help_text="latitude, longitude du lieu de production (tel qu'extrait via un clic-droit sur Google Maps)",
                        max_length=40,
                        null=True,
                        verbose_name="Coordonnées GPS",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        db_index=True,
                        help_text="Doit commencer par http:// ou https://.",
                        null=True,
                        verbose_name="Site web",
                    ),
                ),
                (
                    "fb_page",
                    models.URLField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Page Facebook",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=250,
                        null=True,
                        verbose_name="Adresse email",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        help_text="Peut être un numéro fixe ou GSM.",
                        max_length=128,
                        null=True,
                        region="BE",
                        verbose_name="N° de téléphone",
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        help_text="Cela n'engage à rien d'autre qu'à peut-être un jour être contacté·e.",
                        verbose_name="J'accepte d'être contacté·e par l'UCLouvain pour des questions de recherche liées au maraîchage diversifié.",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Surface dédiée à la production de légumes (en ha)",
                    ),
                ),
                (
                    "FTE",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Nombre d'équivalents temps plein rémunérés",
                    ),
                ),
                (
                    "production",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bio certifié", "Bio certifié"),
                            ("Bio non-certifié", "Bio non-certifié"),
                            ("Conventionnel", "Conventionnel"),
                        ],
                        null=True,
                        verbose_name="Mode de production",
                    ),
                ),
                (
                    "start_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Année d'installation"
                    ),
                ),
                (
                    "end_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Laisser vide si le projet est toujours actif.",
                        null=True,
                        verbose_name="Année de fin d'activité (le cas échéant)",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Commentaire(s)",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si la ferme maraîchère est listée sur la plateforme ou non.",
                        verbose_name="Public",
                    ),
                ),
                (
                    "flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Permet de marquer une ferme en cas de doute sur les données. (Utiliser le champ commentaire pour détailler.)",
                        verbose_name="Flagged",
                    ),
                ),
                (
                    "edited_by_user",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si les données ont été éditées par un·e utilisateur·rice.",
                        verbose_name="Edited by user",
                    ),
                ),
                (
                    "added_by",
                    models.CharField(
                        choices=[("Staff", "Staff"), ("User", "User")],
                        default="User",
                        help_text="Indique si la ferme a été ajoutée par un utilisateur de la plateforme ou non.",
                        verbose_name="Ajouté par",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Parmi les 261 communes wallonnes, les 19 communes bruxelloises et les 6 communes à facilités.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="census.municipality",
                        verbose_name="Commune du lieu de production",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Ferme",
                "verbose_name_plural": "historical Fermes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMarketGardener",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("firstname", models.CharField(max_length=50, verbose_name="Prénom")),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom de famille"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="N° de téléphone personnel.",
                        max_length=128,
                        null=True,
                        region="BE",
                        verbose_name="N° de téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Adresse email personnelle liée au projet si elle existe.",
                        max_length=254,
                        null=True,
                        verbose_name="Adresse email",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="census.farm",
                        verbose_name="Ferme",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Maraîcher·ère",
                "verbose_name_plural": "historical Maraîcher·ères",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
