# Generated by Django 6.0 on 2025-12-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0002_historicalfarm_historicalmarketgardener"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmarketgardener",
            name="farm",
        ),
        migrations.RemoveField(
            model_name="historicalmarketgardener",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="HistoricalFarm",
        ),
        migrations.DeleteModel(
            name="HistoricalMarketGardener",
        ),
    ]
