# Generated by Django 5.2.8 on 2025-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0002_alter_farm_options_alter_marketgardener_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Indique si les donnes ont été confirmées/complétées par un·e maraîcher·ères.",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="flagged",
            field=models.BooleanField(
                default=False,
                help_text="Permet de marquer une ferme en cas de doute sur les données.",
                verbose_name="Flagged",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
    ]
