# Generated by Django 5.2.8 on 2025-12-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0003_farm_confirmed_farm_flagged_farm_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="FTE",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Nombre d'équivalent temps plein (ETP)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Surface (en ha)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="municipality",
            field=models.ForeignKey(
                help_text="Parmi les 261 communes wallonnes, les 19 communes bruxelloises et les 6 communes à facilités.",
                on_delete=django.db.models.deletion.PROTECT,
                to="census.municipality",
                verbose_name="Commune",
            ),
        ),
    ]
