# Generated by Django 6.0 on 2025-12-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0003_remove_historicalmarketgardener_farm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Doit commencer par http:// ou https://.",
                null=True,
                verbose_name="Site web",
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("website", ""), _negated=True),
                fields=("website",),
                name="website_is_not_blank",
            ),
        ),
    ]
