# Generated by Django 5.2.8 on 2025-12-02 15:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0004_alter_farm_fte_alter_farm_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="comment",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Commentaire(s)"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Adresse email",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="end_year",
            field=models.IntegerField(
                blank=True,
                help_text="Laisser vide si le projet est toujours actif.",
                null=True,
                verbose_name="Année de l'arrêt (si fini)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="fb_page",
            field=models.URLField(
                blank=True, null=True, unique=True, verbose_name="Page Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="BE",
                unique=True,
                verbose_name="N° de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="production",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bio certifié", "Bio certifié"),
                    ("Bio non-certifié", "Bio non-certifié"),
                    ("Conventionnel", "Conventionnel"),
                ],
                null=True,
                verbose_name="Mode de production",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="start_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Année d'installation"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Pertinent même si le lien ne fonctionne plus (via Internet Wayback Machine).",
                null=True,
                unique=True,
                verbose_name="Site web",
            ),
        ),
    ]
