# Generated by Django 6.0 on 2025-12-11 15:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0004_alter_farm_website_farm_website_is_not_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Peut être un numéro fixe ou GSM.",
                max_length=128,
                null=True,
                region="BE",
                verbose_name="N° de téléphone",
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone", ""), _negated=True),
                fields=("phone",),
                name="phone_is_not_blank",
            ),
        ),
    ]
