# Generated by Django 6.0 on 2025-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0005_alter_farm_phone_farm_phone_is_not_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                max_length=250, null=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("email",),
                name="email_is_not_blank",
            ),
        ),
    ]
