# Generated by Django 5.2.8 on 2025-12-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0005_alter_farm_comment_alter_farm_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="fb_page",
            field=models.URLField(null=True, verbose_name="Page Facebook"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="website",
            field=models.URLField(
                help_text="Pertinent même si le lien ne fonctionne plus (via Internet Wayback Machine).",
                null=True,
                verbose_name="Site web",
            ),
        ),
    ]
