# Generated by Django 6.0 on 2025-12-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0006_alter_farm_email_farm_email_is_not_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="fb_page",
            field=models.URLField(blank=True, null=True, verbose_name="Page Facebook"),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fb_page", ""), _negated=True),
                fields=("fb_page",),
                name="fb_page_is_not_blank",
            ),
        ),
    ]
