# Generated by Django 6.0 on 2025-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0007_alter_farm_fb_page_farm_fb_page_is_not_blank"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="farm",
            name="website_is_not_blank",
        ),
        migrations.RemoveConstraint(
            model_name="farm",
            name="phone_is_not_blank",
        ),
        migrations.RemoveConstraint(
            model_name="farm",
            name="email_is_not_blank",
        ),
        migrations.RemoveConstraint(
            model_name="farm",
            name="fb_page_is_not_blank",
        ),
        migrations.AlterField(
            model_name="otherlinks",
            name="author",
            field=models.CharField(blank=True, max_length=100, verbose_name="Auteur"),
        ),
        migrations.AlterField(
            model_name="otherlinks",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Titre"),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("website", ""), _negated=True),
                fields=("website",),
                name="website_unique",
                violation_error_code="website_unique",
                violation_error_message="Le site web indiquée est déjà utilisée par une ferme.",
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone", ""), _negated=True),
                fields=("phone",),
                name="phone_unique",
                violation_error_message="Le numéro de téléphone indiquée est déjà utilisée par une ferme.",
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("email",),
                name="email_unique",
                violation_error_message="L'adresse e-mail indiquée est déjà utilisée par une ferme.",
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fb_page", ""), _negated=True),
                fields=("fb_page",),
                name="fb_page_unique",
                violation_error_message="La page Facebook indiquée est déjà utilisée par une ferme.",
            ),
        ),
    ]
