# Generated by Django 5.2.8 on 2025-12-03 08:18

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0007_alter_farm_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region="BE", verbose_name="N° de téléphone"
            ),
        ),
    ]
