# Generated by Django 5.2.8 on 2025-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0008_alter_farm_email_alter_farm_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                default=None,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Adresse email",
            ),
        ),
    ]
