# Generated by Django 6.0 on 2025-12-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0008_remove_farm_website_is_not_blank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="research_priorities",
            field=models.TextField(
                blank=True,
                verbose_name="Selon vous, quelles devraient être les priorités de la recherche sur le maraîchage ?",
            ),
        ),
    ]
