# Generated by Django 6.0 on 2025-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0009_farm_research_priorities"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="GPS_coordinates",
            field=models.CharField(
                blank=True,
                help_text="latitude, longitude de la commune (tel que fournit dans le .geojson des communes belges).",
                max_length=40,
                verbose_name="Coordonnées GPS",
            ),
        ),
    ]
