# Generated by Django 5.2.8 on 2025-12-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0009_alter_farm_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                default=None, max_length=254, null=True, verbose_name="Adresse email"
            ),
        ),
    ]
