# Generated by Django 6.0 on 2025-12-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0010_municipality_gps_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="cgu_consent",
            field=models.BooleanField(default=False, verbose_name="CGU"),
        ),
    ]
