# Generated by Django 5.2.8 on 2025-12-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0010_alter_farm_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="GPS_coordinates",
            field=models.CharField(
                blank=True,
                help_text="latitude, longitude (tel qu'extrait via un clic-droit sur Google Maps)",
                max_length=36,
                verbose_name="Coordonnées GPS",
            ),
        ),
    ]
