# Generated by Django 6.0 on 2026-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0011_farm_cgu_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="cover_crop",
            field=models.BooleanField(
                choices=[(None, "/"), (True, "Oui"), (False, "Non")],
                default=None,
                help_text="Pourquoi cette question ? Dans le cadre de ma thèse, j'aimerai étudier la pratiques des couverts végétaux dans le contexte du maraîchage diversifié.",
                null=True,
                verbose_name="Intégrez-vous des couverts végétaux dans votre rotation ?",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="why_no_cover_crop",
            field=models.TextField(
                blank=True,
                help_text="Par exemple : perte de rentabilité par rapport à une culture de légumes, rotation trop dense, pas assez d'espace, pas le temps, manque de références techniques suffisamment solides, manque d'équipement adapté (semis ou destruction des couverts), coût des semences, etc.",
                verbose_name="Si vous n'intégrez pas de couverts végétaux dans votre rotation, pour quelle(s) raison(s) ?",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="research_priorities",
            field=models.TextField(
                blank=True,
                help_text="De quoi avez-vous besoin ? Qu'est-ce qui vous serait utile ? À quels problèmes êtes vous confronté·es ? Qu'aimeriez-vous améliorer ?",
                verbose_name="Selon vous, quelles devraient être les priorités de la recherche sur le maraîchage ?",
            ),
        ),
    ]
