# Generated by Django 5.2.8 on 2025-12-03 08:44

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0011_alter_farm_gps_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="Adresse email",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="BE",
                verbose_name="N° de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Pertinent même si le lien ne fonctionne plus (via Internet Wayback Machine).",
                null=True,
                verbose_name="Site web",
            ),
        ),
    ]
