# Generated by Django 5.2.8 on 2025-12-03 08:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0012_alter_farm_email_alter_farm_phone_alter_farm_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketgardener",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None,
                max_length=128,
                null=True,
                region="BE",
                unique=True,
                verbose_name="N° de téléphone",
            ),
        ),
    ]
