# Generated by Django 6.0 on 2026-02-23 08:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0012_farm_cover_crop_farm_why_no_cover_crop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="FTEv",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Idem, mais pour la main d'oeuvre non-rémunérées, en moyenne sur une année. Exemples : aide familiale bénévole, stagiaires, volontaires, etc. <b>(Pour la production de légumes seulement.)</b>",
                max_digits=4,
                null=True,
                verbose_name="Nombre d'équivalents temps plein <u>non</u>-rémunérés",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="FTE",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Il s'agit d'une <i>estimation</i> du nombre moyen de personnes travaillant à temps plein sur une année pour la production de légumes. Exemples : vous à temps plein + 1 autre personne à mi-temps toute l'année + 1 saisonnier·ère pour un tiers de l'année = 1 + 1/2 + 1/3 = environ 1.8 équivalents temps plein rémunérés. <b>(Pour la production de légumes  seulement.)</b>",
                max_digits=4,
                null=True,
                verbose_name="Nombre d'équivalents temps plein <u>rémunérés</u>",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Nom de la rue et numéro du lieu de production.",
                max_length=250,
                null=True,
                verbose_name="Adresse du lieu de <u>production</u>",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sans compter les éventuelles autres activités agricoles : élevage, verger, petits fruits, etc.",
                max_digits=4,
                null=True,
                verbose_name="Surface brute dédiée à la production de légumes (en <b>ha</b>)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="consent",
            field=models.BooleanField(
                default=False,
                help_text="Cela n'engage à rien d'autre qu'à peut-être un jour être contacté·e par un·e chercheur·se.",
                verbose_name="J'accepte d'être contacté·e par l'UCLouvain pour des questions de recherche liées au maraîchage diversifié.",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="cover_crop",
            field=models.BooleanField(
                choices=[(None, "/"), (True, "Oui"), (False, "Non")],
                default=None,
                null=True,
                verbose_name="Intégrez-vous des couverts végétaux dans votre rotation ?",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                help_text="Cette adresse vous permettra de modifier les informations liées à votre ferme via la plateforme. Vous serez également contacté·e une fois par an pour mettre à jour vos données et les compléter (de nouvelles questions apparaîtront d'année en année sur la plateforme).",
                max_length=250,
                null=True,
                verbose_name="Adresse email",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="end_year",
            field=models.IntegerField(
                blank=True,
                help_text="Laissez vide si le projet est toujours actif. <b>Si le projet n'est plus actif, complétez ce champ pour ne plus être affiché sur la plateforme.</b>",
                null=True,
                verbose_name="Année de <b>fin</b> d'activité (le cas échéant)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="name",
            field=models.CharField(
                help_text='Attention, vérifiez bien que votre ferme ne se trouve pas déjà dans la <a href="../listing/">liste</a> ou sur la <a href="../map/">carte</a>.',
                max_length=250,
                verbose_name="Nom de la ferme",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Fixe ou GSM.",
                max_length=128,
                null=True,
                region="BE",
                verbose_name="N° de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="research_priorities",
            field=models.TextField(
                blank=True,
                help_text="À quels problèmes êtes vous confronté·es ? Qu'aimeriez-vous améliorer ? Quels sont vos besoins ? Qu'est-ce qui vous serait utile ?",
                verbose_name="Selon vous, quelles devraient être les priorités de la recherche sur le maraîchage ?",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="why_no_cover_crop",
            field=models.TextField(
                blank=True,
                help_text="Par exemple : perte de rentabilité par rapport à une culture de légume, rotation trop dense, pas assez d'espace, pas le temps, manque de références techniques suffisamment solides, manque d'équipement adapté (semis ou destruction des couverts), coût des semences, etc.",
                verbose_name="Si vous n'intégrez <b>pas</b> de couverts végétaux dans votre rotation, pour quelle(s) raison(s) ?",
            ),
        ),
    ]
