# Generated by Django 6.0 on 2026-02-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0013_farm_ftev_alter_farm_fte_alter_farm_address_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="municipality",
        #     name="email",
        #     field=models.EmailField(
        #         blank=True,
        #         help_text="Permet de contacter les communes pour améliorer le recensement.",
        #         max_length=250,
        #         null=True,
        #         verbose_name="Adresse e-mail",
        #     ),
        # ),
        migrations.AlterField(
            model_name="farm",
            name="FTE",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Il s'agit d'une <i>estimation</i> du nombre moyen de personnes travaillant à temps plein sur une année pour la production de légumes. Exemples : <u>vous</u> à temps plein + 1 autre personne à mi-temps toute l'année + 1 saisonnier·ère pour un tiers de l'année = 1 + 1/2 + 1/3 = environ 1.8 équivalents temps plein rémunérés. <b>(Pour la production de légumes  seulement.)</b>",
                max_digits=4,
                null=True,
                verbose_name="Nombre d'équivalents temps plein <u>rémunérés</u> (vous inclus)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="FTEv",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Idem, mais pour la main d'oeuvre non-rémunérée, en moyenne sur une année. Exemples : aide familiale bénévole, stagiaires, volontaires, etc. <b>(Pour la production de légumes seulement.)</b>",
                max_digits=4,
                null=True,
                verbose_name="Nombre d'équivalents temps plein <u>non</u>-rémunérés",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sans compter les éventuelles autres activités agricoles : élevage, verger, petits fruits, etc.",
                max_digits=4,
                null=True,
                verbose_name="Surface brute <u>dédiée à la production de légumes</u> (en <b>ha</b>)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="cgu_consent",
            field=models.BooleanField(
                default=False,
                help_text="Les conditions générales d'utilisation s'ouvriront dans un nouvel onglet pour vous éviter de perdre les données complétées dans le formulaire.",
                verbose_name="CGU",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="edited_by_user",
            field=models.BooleanField(
                default=True,
                help_text="Indique si les données ont été éditées par le/la maraîcher·ère concernée.",
                verbose_name="Modifiée par le/la maraîche·ère",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="flagged",
            field=models.BooleanField(
                default=False,
                help_text="Permet de marquer une ferme en cas de doute sur les données. (Utiliser le champ commentaire pour détailler.)",
                verbose_name="Marquée",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="start_year",
            field=models.IntegerField(
                blank=True,
                help_text="En quelle année avez-vous démarré votre projet de maraîchage ?",
                null=True,
                verbose_name="Année d'installation",
            ),
        ),
    ]
