# Generated by Django 5.2.8 on 2025-12-03 08:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0013_alter_marketgardener_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketgardener",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                region="BE",
                unique=True,
                verbose_name="N° de téléphone",
            ),
        ),
    ]
