# Generated by Django 5.2.8 on 2025-12-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0014_alter_marketgardener_phone"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marketgardener",
            unique_together={("firstname", "lastname")},
        ),
    ]
