# Generated by Django 6.0 on 2026-02-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0014_municipality_email_alter_farm_fte_alter_farm_ftev_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="alt_email",
            field=models.EmailField(
                blank=True,
                help_text="Au cas où une 2e adresse semble pertinente.",
                max_length=250,
                null=True,
                verbose_name="Adresse e-mail alternative",
            ),
        ),
    ]
