# Generated by Django 5.2.8 on 2025-12-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0015_alter_marketgardener_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="fb_page",
            field=models.URLField(blank=True, null=True, verbose_name="Page Facebook"),
        ),
        migrations.AlterField(
            model_name="farm",
            name="website",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="Pertinent même si le lien ne fonctionne plus (via Internet Wayback Machine).",
                null=True,
                verbose_name="Site web",
            ),
        ),
    ]
