# Generated by Django 6.0 on 2026-02-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0015_municipality_alt_email_municipality_alt_email2_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="municipality",
        #     name="alt_email",
        # ),
        migrations.RemoveField(
            model_name="municipality",
            name="alt_email2",
        ),
        migrations.RemoveField(
            model_name="municipality",
            name="alt_email3",
        ),
        # migrations.RemoveField(
        #     model_name="municipality",
        #     name="email",
        # ),
    ]
