# Generated by Django 6.0 on 2026-02-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0015_municipality_alt_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="alt_email2",
            field=models.EmailField(
                blank=True,
                help_text="Au cas où une 3e adresse semble pertinente.",
                max_length=250,
                null=True,
                verbose_name="2e adresse e-mail alternative",
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="alt_email3",
            field=models.EmailField(
                blank=True,
                help_text="Au cas où une 4e adresse semble pertinente.",
                max_length=250,
                null=True,
                verbose_name="3e adresse e-mail alternative",
            ),
        ),
    ]
