# Generated by Django 5.2.8 on 2025-12-03 10:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0016_alter_farm_fb_page_alter_farm_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketgardener",
            name="mail",
            field=models.EmailField(
                blank=True,
                default=None,
                help_text="Adresse email personnelle liée au projet si elle existe.",
                max_length=254,
                null=True,
                verbose_name="Adresse email",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="GPS_coordinates",
            field=models.CharField(
                blank=True,
                help_text="latitude, longitude (tel qu'extrait via un clic-droit sur Google Maps)",
                max_length=36,
                null=True,
                verbose_name="Coordonnées GPS",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="fb_page",
            field=models.URLField(
                blank=True, null=True, unique=True, verbose_name="Page Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="BE",
                unique=True,
                verbose_name="N° de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Pertinent même si le lien ne fonctionne plus (via Internet Wayback Machine).",
                null=True,
                unique=True,
                verbose_name="Site web",
            ),
        ),
    ]
