# Generated by Django 6.0 on 2026-02-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0016_remove_municipality_alt_email_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="municipality",
        #     name="alt_email",
        #     field=models.EmailField(
        #         blank=True,
        #         help_text="Au cas où une 2e adresse semble pertinente.",
        #         max_length=250,
        #         null=True,
        #         verbose_name="Adresse e-mail alternative",
        #     ),
        # ),
        migrations.AddField(
            model_name="municipality",
            name="alt_email2",
            field=models.EmailField(
                blank=True,
                help_text="Au cas où une 3e adresse semble pertinente.",
                max_length=250,
                null=True,
                verbose_name="2e adresse e-mail alternative",
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="alt_email3",
            field=models.EmailField(
                blank=True,
                help_text="Au cas où une 4e adresse semble pertinente.",
                max_length=250,
                null=True,
                verbose_name="3e adresse e-mail alternative",
            ),
        ),
        # migrations.AddField(
        #     model_name="municipality",
        #     name="email",
        #     field=models.EmailField(
        #         blank=True,
        #         help_text="Permet de contacter les communes pour améliorer le recensement.",
        #         max_length=250,
        #         null=True,
        #         verbose_name="Adresse e-mail",
        #     ),
        # ),
    ]
