# Generated by Django 5.2.8 on 2025-12-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0017_marketgardener_mail_alter_farm_gps_coordinates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketgardener",
            name="mail",
            field=models.EmailField(
                blank=True,
                default=None,
                help_text="Adresse email personnelle liée au projet si elle existe.",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Adresse email",
            ),
        ),
    ]
