# Generated by Django 5.2.8 on 2025-12-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0021_alter_farm_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=250,
                null=True,
                unique=True,
                verbose_name="Adresse email",
            ),
        ),
    ]
