# Generated by Django 5.2.8 on 2025-12-03 10:31

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0022_alter_farm_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketgardener",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default=None,
                help_text="N° de téléphone personnel.",
                max_length=128,
                null=True,
                region="BE",
                unique=True,
                verbose_name="N° de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="otherlinks",
            name="link",
            field=models.URLField(
                help_text="Pertinent même si le lien ne fonctionne plus (via Internet Wayback Machine).",
                unique=True,
                verbose_name="Lien",
            ),
        ),
    ]
