# Generated by Django 5.2.8 on 2025-12-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0023_alter_marketgardener_phone_alter_otherlinks_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketgardener",
            old_name="mail",
            new_name="email",
        ),
    ]
