# Generated by Django 5.2.8 on 2025-12-08 07:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0024_rename_mail_marketgardener_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="FTE",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="ETP",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="GPS_coordinates",
            field=models.CharField(
                blank=True,
                help_text="latitude, longitude (tel qu'extrait via un clic-droit sur Google Maps)",
                max_length=40,
                null=True,
                verbose_name="Coordonnées GPS",
            ),
        ),
        migrations.AlterField(
            model_name="otherlinks",
            name="link",
            field=models.URLField(unique=True, verbose_name="Lien"),
        ),
        migrations.CreateModel(
            name="ExpiringUniqueEditLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default="QYIRJz3un3DJkYdxWZdh1L9YP1QH7BWv8Qi8oYpZaBl21M6nKozCn9XJshh7",
                        editable=False,
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 12, 9, 7, 23, 34, 288275, tzinfo=datetime.timezone.utc
                        ),
                        editable=False,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="census.farm",
                        verbose_name="Ferme associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien d'édition",
                "verbose_name_plural": "Liens d'édition",
            },
        ),
    ]
