# Generated by Django 5.2.8 on 2025-12-08 11:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0025_alter_farm_fte_alter_farm_gps_coordinates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 9, 12, 42, 15, 573624)
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="census.farm",
                verbose_name="Ferme associée",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="eGZtgmmGwadYQEU2lqIOxOz0MlveAPX4zaOFvaSNDFwFd5RgS2oxRtqfqm0u",
                max_length=120,
                unique=True,
            ),
        ),
    ]
