# Generated by Django 5.2.8 on 2025-12-08 15:02

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0026_alter_expiringuniqueeditlink_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Nom de la rue et numéro du lieu de production.",
                max_length=250,
                null=True,
                verbose_name="Adresse du lieu de production",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="consent",
            field=models.BooleanField(
                default=False,
                verbose_name="J'accepte d'être contacté·e par l'UCLouvain pour des questions de recherche liées au maraîchage diversifié.",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 9, 16, 2, 46, 207076),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="eMWlbbPnLKKTl6rkAFBIJXl1QU9Jeq7bT7OCfz0mYj2UZGpgDX5Wp10FSWfx",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="FTE",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="Nombre d'équivalents temps plein rémunérés",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="GPS_coordinates",
            field=models.CharField(
                blank=True,
                help_text="latitude, longitude du lieu de production (tel qu'extrait via un clic-droit sur Google Maps)",
                max_length=40,
                null=True,
                verbose_name="Coordonnées GPS",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Surface dédiée à la production de légumes (en ha)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="end_year",
            field=models.IntegerField(
                blank=True,
                help_text="Laisser vide si le projet est toujours actif.",
                null=True,
                verbose_name="Année de fin d'activité (le cas échéant)",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="municipality",
            field=models.ForeignKey(
                help_text="Parmi les 261 communes wallonnes, les 19 communes bruxelloises et les 6 communes à facilités.",
                on_delete=django.db.models.deletion.PROTECT,
                to="census.municipality",
                verbose_name="Commune du lieu de production",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Peut être un numéro fixe ou GSM.",
                max_length=128,
                null=True,
                region="BE",
                unique=True,
                verbose_name="N° de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="website",
            field=models.URLField(
                blank=True, null=True, unique=True, verbose_name="Site web"
            ),
        ),
    ]
