# Generated by Django 5.2.8 on 2025-12-09 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0027_farm_address_farm_consent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 8, 46, 33, 631061),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="5Fd0hdlyhaQ6Pn7xccVRnCLL8Wzl2vfnAeiQ1uef3Om6QoIQF5t2rPq84ztz",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Indique si les données ont été confirmées/complétées par un·e maraîcher·ères.",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="email",
            field=models.EmailField(
                max_length=250, null=True, unique=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Doit commencer par http:// ou https://.",
                null=True,
                unique=True,
                verbose_name="Site web",
            ),
        ),
    ]
