# Generated by Django 5.2.8 on 2025-12-09 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0028_alter_expiringuniqueeditlink_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 8, 46, 39, 42651),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="SiBGwTJ3lEfrr5tPStxc5qaytaUpV2aeRovCTiidVtDV1hoIdNx2cr0nMRJm",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
    ]
