# Generated by Django 5.2.8 on 2025-12-09 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0030_alter_expiringuniqueeditlink_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 9, 17, 48, 404007),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="DCOwYXyFCuUrpS5yUk0gZ6gl8kwJJfWt4O2I14HjIeJJNGtE19fgt2UbTVUL",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
        migrations.AlterField(
            model_name="marketgardener",
            name="firstname",
            field=models.CharField(max_length=50, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="marketgardener",
            name="lastname",
            field=models.CharField(max_length=100, verbose_name="Nom de famille"),
        ),
    ]
