# Generated by Django 5.2.8 on 2025-12-09 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0031_alter_expiringuniqueeditlink_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 14, 57, 4, 602022),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="spWj3SXIsNWniWKFLvnfTFCr4IYxipgfvhvW8Wz378prETHZ8QadWI6ImYL7",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
    ]
