# Generated by Django 5.2.8 on 2025-12-09 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0032_farm_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="added_by",
            field=models.CharField(
                choices=[
                    ("Bio certifié", "Bio certifié"),
                    ("Bio non-certifié", "Bio non-certifié"),
                    ("Conventionnel", "Conventionnel"),
                ],
                default="User",
                verbose_name="Ajouté par",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 15, 38, 28, 790980),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="ZefzR5dYOOJ4imkVtDaVSDFc8QnhxvJKKSn9H5tlKf9HCQGc8wWEwZxSabwj",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
    ]
