# Generated by Django 5.2.8 on 2025-12-09 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0033_farm_added_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 15, 39, 14, 151703),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="65Gl7JrTO8SlaSYGRUlvCGVVLTcGXkwhjUS9u5SJ9FVXUvOWnhouOvzNo8D0",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
    ]
