# Generated by Django 5.2.8 on 2025-12-09 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0034_alter_expiringuniqueeditlink_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 15, 41, 42, 207361),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="fy8plwolmsBi65pu5cYpCi9uXVMqy7uINoef5mqPkPtjcUCtr0sA3YDvqYlJ",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="added_by",
            field=models.CharField(
                choices=[("Staff", "Staff"), ("User", "User")],
                default="User",
                verbose_name="Ajouté par",
            ),
        ),
    ]
