# Generated by Django 5.2.8 on 2025-12-09 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0035_alter_expiringuniqueeditlink_expiration_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm",
            name="confirmed",
        ),
        migrations.AddField(
            model_name="farm",
            name="edited_by_user",
            field=models.BooleanField(
                default=False,
                help_text="Indique si les données ont été éditées par un·e utilisateur·rice.",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 15, 51, 24, 322526),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="yspD1BehSnfuGcZ0zuUn3hCerwibCoVxghYSwS9rqCGp2AXvI92Jl9BOnJ8E",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="added_by",
            field=models.CharField(
                choices=[("Staff", "Staff"), ("User", "User")],
                default="User",
                help_text="Indique si la ferme a été ajoutée par un utilisateur de la plateforme ou non.",
                verbose_name="Ajouté par",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="flagged",
            field=models.BooleanField(
                default=False,
                help_text="Permet de marquer une ferme en cas de doute sur les données. (Utiliser le champ commentaire pour détailler.)",
                verbose_name="Flagged",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Indique si la ferme maraîchère est listée sur la plateforme ou non.",
                verbose_name="Public",
            ),
        ),
    ]
