# Generated by Django 5.2.8 on 2025-12-09 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0036_remove_farm_confirmed_farm_edited_by_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 16, 2, 7, 134424),
                verbose_name="Date d'expiration",
            ),
        ),
        migrations.AlterField(
            model_name="expiringuniqueeditlink",
            name="token",
            field=models.CharField(
                default="549sPZfrngJAPh10BtNsQwdwiUx8dpfy7kCSy95bdHQWIAZOsciXt3F1F4aQ",
                max_length=120,
                unique=True,
                verbose_name="Token d'accès unique",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="edited_by_user",
            field=models.BooleanField(
                default=True,
                help_text="Indique si les données ont été éditées par un·e utilisateur·rice.",
                verbose_name="Modifié par utilisateur",
            ),
        ),
    ]
